name: transmission
description: Flutter package to talk to a Transmission torrent instance
version: 0.0.2
homepage: https://github.com/mylisabox/transmission

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: '>=3.0.10 <4.0.0'

dev_dependencies:
