name: transmission
description: Flutter package to talk to a Transmission torrent instance
version: 0.1.1
homepage: https://github.com/mylisabox/transmission

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dio: '^5.3.2'

dev_dependencies:
