name: transmission
description: Flutter package to talk to a Transmission torrent instance
version: 0.0.1
homepage: https://github.com/jaumard/transmission

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^3.0.10

dev_dependencies:
